### ISSUE TITLE
Documentation lacking

### ISSUE THREAD

**Issue by welschmoor** [PizzasBear/templr#2]
Hey!

Iooks interesting, but very hard to get going because documentation is lacking. I could not even create a second component to use inside the first one, how do I do that? It renders string `<button>"yes"</... ` instead of an actual button:

```
//this does not work, using button() inside the layout
pub fn root_layout(name: &str) -> templ_ret!['_] {
    templ! {
       <div>
          <p>Hello, {name}!</p>
          {button("yes")}
       </div>
    }
}


pub fn button(textx: &str) -> templ_ret!['_] {
    templ! {
        <button>{text}</p>
    }
}

```

It would be nice if you catered it to people like me by providing documentation which can be followed by a 5 year old :D

**Comment by PizzasBear** [comment]
I did put an explanation about template composition here: [docs rs](https://docs.rs/templr/0.2.2/templr/macro.templ.html#template-composition).

Is the current documentation not clear enough?

**Comment by PizzasBear** [comment]
In your example, I would do the following:
```rust
pub fn root_layout(name: &str) -> templ_ret!['_] {
    templ! {
       <div>
          <p>Hello, {name}!</p>
          #button("yes"); // This is the template instantiation syntax
       </div>
    }
}


pub fn button(text: &str) -> templ_ret!['_] {
    templ! {
        <button>{text}</button>
    }
}
```
